name: publish-package
run-name: publish to mooncakes
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - uses: actions/checkout@v4
      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: moon version
        run: |
          moon version --all
          moonrun --version
      - name: moon check
        run: |
          moon install
          moon check --target all
      - name: publish
        run: |
          node ./rm_deps.js
          echo $SECRET > ~/.moon/credentials.json
          moon publish
          rm ~/.moon/credentials.json
        env:
          SECRET: ${{ secrets.MOONCAKES_MOONBITLANG_TOKEN }}
